GET http://localhost:3000/api/univ HTTP/1.1

###

POST http://localhost:3000/api/univ/relationship/SciencesPD/Polytech HTTP/1.1
content-type: application/json

{
    "miles": 1521121
}

###

DELETE http://localhost:3000/api/univ/relationship/Yale%20University/Cornell%20University HTTP/1.1

###

DELETE http://localhost:3000/api/univ/Yale%20University/relationship HTTP/1.1

###

DELETE http://localhost:3000/api/univ/SciencesPD HTTP/1.1